[package]
name = "psrsee"
version = "0.0.1"
description = "psrsee outputs a process tree in JSON machine-readable format"

[[bin]]
name = "psrsee"
path = "psrsee.rs"

[dependencies]
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.122"
